#!/usr/bin/env python3

import dymoprint
dp = dymoprint

def main():
  print("At the start of MAIN")

  lm = dymoprint.DymoLabeler("/dev/null")
  tempLabel = lm.create_label("Foo")
  preview = lm.previewLabel(tempLabel)
  try:
    with open("preview.jpeg", "w") as file:
      preview.save(file, "JPEG");
  except IOError as e:

      print >> sys.stderr, "dymoprint: error generating preview:{}".\
          format(e)
      labelimage.show()
  print("Saved preview to 'preview.jpg'")





if __name__ == '__main__':
  main()
